version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_USER=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - 5432:5432
    volumes:
      - ./config_pg/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080